### ISSUE TITLE
[Bug]IQapTcha无法滑动

### ISSUE THREAD

**Issue by misaka10843** [typecho-fans/plugins#148]
## 相关信息

在按需添加了`<div id="QapTcha"></div>`后，虽然显示了滑动条，但是只要鼠标点击此条就会出现下面的错误
```
Uncaught TypeError: a(...).find(...).andSelf is not a function
    at a.<computed>.<computed>._getHandle (jquery-ui.js:21:4094)
    at a.<computed>.<computed>._mouseCapture (jquery-ui.js:21:1080)
    at a.<computed>.<computed>._mouseDown (jquery-ui.js:13:936)
    at HTMLDivElement.<anonymous> (jquery-ui.js:13:238)
    at HTMLDivElement.dispatch (jquery.min.js:2:41772)
    at y.handle (jquery.min.js:2:39791)
    at HTMLDivElement.c (rocket-loader.min.js:1:9405)
_getHandle @ jquery-ui.js:21
_mouseCapture @ jquery-ui.js:21
_mouseDown @ jquery-ui.js:13
(匿名) @ jquery-ui.js:13
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
c @ rocket-loader.min.js:1
```

在插件设置中jq加载方式两个都试过，但是似乎还是不行

## 相关版本与主题信息

主题：`HandSome`
typecho版本：`1.2.0`

## 相关截图

插件列表：
![image](https://user-images.githubusercontent.com/69132853/173487482-667322e9-aeea-44cf-93ef-0a676dcc1e69.png)

报错截图：
![image](https://user-images.githubusercontent.com/69132853/173487619-56abee5b-49f2-4464-9443-af88eae92078.png)

**Comment by misaka10843** [comment]
似乎是因为jq ui的版本过低导致主题jq版本过高导致andSelf被弃用，现在暂时可以更换高版本解决问题
