### ISSUE TITLE
typecho 使用links插件在新增链接时报错

### ISSUE THREAD

**Issue by hiBlunt** [typecho-fans/plugins#166]
links插件版本：1.2.3
typecho版本：1.2.1
数据库：sqlite3
php版本：8.0.0

报错信息：
```
SQLSTATE[HY000]: General error: 20 datatype mismatch
Typecho\Db\Adapter\SQLException: SQLSTATE[HY000]: General error: 20 datatype mismatch in /var/www/html/typecho-blog/var/Typecho/Db/Adapter/Pdo.php:111
Stack trace:
#0 /var/www/html/typecho-blog/var/Typecho/Db.php(391): Typecho\Db\Adapter\Pdo->query('INSERT INTO blo...', Object(PDO), 2, 'INSERT', 'blog_links')
#1 /var/www/html/typecho-blog/usr/plugins/Links/Action.php(35): Typecho\Db->query(Object(Typecho\Db\Query))
#2 /var/www/html/typecho-blog/usr/plugins/Links/Action.php(155): Links_Action->insertLink()
#3 /var/www/html/typecho-blog/var/Widget/Action.php(71): Links_Action->action()
#4 /var/www/html/typecho-blog/var/Typecho/Widget.php(155): Widget\Action->execute()
#5 /var/www/html/typecho-blog/var/Typecho/Router.php(96): Typecho\Widget::widget('\\Widget\\Action', NULL, Array)
#6 /var/www/html/typecho-blog/index.php(23): Typecho\Router::dispatch()
#7 {main}
```

**Comment by q25853** [comment]
我也是这样

**Comment by benzBrake** [comment]
最新版本已经 1.2.6 了 https://github.com/Mejituu/Links

**Comment by hiBlunt** [comment]
@benzBrake 感谢您的回复，更换为1.2.6版本后已经可以正常使用。

**Comment by hiBlunt** [comment]
问题已解决，issue关闭
